export default {
  DEFAULT_NUMBER_OF_COLORS: 8,
  DEFAULT_GRID_SIZE: 10,
  HEX_VALUES: '0123456789ABCDEF',
  MARGIN_COMPENSATION_PIXELS: 30,
  BORDER_COMPENSATION_PIXELS: 1,
  LEFT_COMMAND_KEY: 91,
  RIGHT_COMMAND_KEY: 93,
  FORCE_COLOR_REFRESH: true
};
